// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/change-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/change-password.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/contact/request': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/contact/request.post').default>>>>
    }
    '/api/factura/cfdi/:uid/:format': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/factura/cfdi/[uid]/[format].get').default>>>>
    }
    '/api/factura/cfdi/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/factura/cfdi/create.post').default>>>>
    }
    '/api/factura/cfdi/global': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/factura/cfdi/global.post').default>>>>
    }
    '/api/factura/cfdi': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/factura/cfdi/index.get').default>>>>
    }
    '/api/factura/clients/:uid': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/factura/clients/[uid].delete').default>>>>
    }
    '/api/factura/clients': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/factura/clients/index.get').default>>>>
    }
    '/api/factura/clients/sync': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/factura/clients/sync.post').default>>>>
    }
    '/api/factura/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/factura/orders.get').default>>>>
    }
    '/api/notifications/:id/read': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/[id]/read.post').default>>>>
    }
    '/api/notifications': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/index.get').default>>>>
    }
    '/api/notifications/read-all': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/notifications/read-all.post').default>>>>
    }
    '/api/orders/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[id].patch').default>>>>
    }
    '/api/orders/:id/retry-syscom': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[id]/retry-syscom.post').default>>>>
    }
    '/api/orders/:id/syscom-track': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[id]/syscom-track.get').default>>>>
    }
    '/api/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/index.post').default>>>>
    }
    '/api/syscom/**:path': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/syscom/[...path]').default>>>>
    }
    '/api/users/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id].patch').default>>>>
    }
    '/api/users/:id/fiscal': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]/fiscal.patch').default>>>>
    }
    '/api/users/fiscal-data': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/fiscal-data.patch').default>>>>
    }
    '/api/users/fiscal': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/fiscal.get').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}